# Generated by Django 4.1.3 on 2023-02-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={},
        ),
        migrations.AlterModelOptions(
            name='companyspheres',
            options={},
        ),
        migrations.AlterModelOptions(
            name='companytypes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fieldspheres',
            options={},
        ),
        migrations.AlterModelOptions(
            name='managersinevents',
            options={},
        ),
        migrations.AlterModelOptions(
            name='participantsinevents',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectfields',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectgrades',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentsinprojects',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teachersinevents',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teachersinprojects',
            options={},
        ),
        migrations.AlterModelOptions(
            name='universities',
            options={},
        ),
    ]
