# Generated by Django 4.1.3 on 2023-02-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_companies_company_sphere_companies_company_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='is_frozen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsinprojects',
            name='is_curator',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='studentsinprojects',
            name='is_moderator',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='studentsinprojects',
            name='team',
            field=models.SmallIntegerField(default=None),
        ),
    ]
