# Generated by Django 4.1.3 on 2023-02-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_companies_company_sphere_companies_company_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinprojects',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='homepage.projects'),
        ),
        migrations.AlterField(
            model_name='studentsinprojects',
            name='student_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homepage.students'),
        ),
    ]
