# Generated by Django 4.1.1 on 2022-09-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=150)),
                ('ever_married', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('graduated', models.CharField(max_length=150)),
                ('profession', models.CharField(max_length=150)),
                ('work_experience', models.FloatField()),
                ('spending_score', models.CharField(max_length=150)),
                ('family_size', models.FloatField()),
                ('var_1', models.CharField(max_length=150)),
            ],
        ),
    ]
