# Generated by Django 4.1.3 on 2023-02-12 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_companies_options_alter_companyspheres_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='company_sphere',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.companyspheres'),
        ),
        migrations.AddField(
            model_name='companies',
            name='company_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.companytypes'),
        ),
        migrations.AddField(
            model_name='events',
            name='event_region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.regions'),
        ),
        migrations.AddField(
            model_name='managersinevents',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.events'),
        ),
        migrations.AddField(
            model_name='managersinevents',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.students'),
        ),
        migrations.AddField(
            model_name='participantsinevents',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.events'),
        ),
        migrations.AddField(
            model_name='participantsinevents',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.students'),
        ),
        migrations.AddField(
            model_name='projectfields',
            name='sphere',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.fieldspheres'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.companies'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_field',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.projectfields'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_grade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.projectgrades'),
        ),
        migrations.AddField(
            model_name='students',
            name='bachelors_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.universities'),
        ),
        migrations.AddField(
            model_name='students',
            name='masters_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mastersuni', to='homepage.universities'),
        ),
        migrations.AddField(
            model_name='studentsinprojects',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homepage.projects'),
        ),
        migrations.AddField(
            model_name='studentsinprojects',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homepage.students'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='teacher_university',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.universities'),
        ),
        migrations.AddField(
            model_name='teachersinevents',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.events'),
        ),
        migrations.AddField(
            model_name='teachersinevents',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.teachers'),
        ),
        migrations.AddField(
            model_name='teachersinprojects',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homepage.projects'),
        ),
        migrations.AddField(
            model_name='teachersinprojects',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homepage.teachers'),
        ),
        migrations.AddField(
            model_name='universities',
            name='university_region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.regions'),
        ),
    ]
