# Generated by Django 4.1.3 on 2023-01-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_amogus_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='amogus',
            name='group',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
