# Generated by Django 4.1.3 on 2023-02-12 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_companies_options_alter_companyspheres_options_and_more'),
    ]

    operations = [
        ]
