from django.urls import path, include
from .views import *
urlpatterns = [
    path('', homepage),
    path('accounts/', include('django.contrib.auth.urls')),
    path('company-form/', createCompany, name='company-form'),
    path('student-form/', student_view, name='student-form'),
    path('universities-form/', student_view, name='universities-form'),
    path('teachers-form/', student_view, name='teachers-form'),
    path('events-form/', add_event, name='events-form'),
    path('projects-form/', add_project, name='projects-form'),
    path('projects-form/<str:pk>/', edit_project, name='edit-project-form'),
    path('company-hub/', companyHub, name='company-hub'),
    path('project-hub/', projectHub, name='project-hub'),
    path('update-company-form/<str:pk>/', updateCompany, name='update-company-form'),
    path('delete-company-form/<str:pk>/', deleteCompany, name='delete-company-form'),
    path('update-project-form/<str:pk>/', edit_project, name='update-project-form'),
    path('update-student-hub/<str:pk>/', edit_students, name='update-student-hub'),
    path('update-student-form/<str:pk>/', edit_students_form, name='update-student-form'),
    path('delete-student-form/<str:pk>/', delete_students, name='delete-student-form'),
    path('update-teacher-hub/<str:pk>/', edit_teachers, name='update-teacher-hub'),
    path('update-teacher-form/<str:pk>/', edit_teachers_form, name='update-teacher-form'),
    path('delete-teacher-form/<str:pk>/', delete_teachers, name='delete-teacher-form'),
    path('delete-project-form/<str:pk>/', delete_project, name='delete-project-form'),
    path('event-hub/', eventHub, name='event-hub'),
    path('update-event-form/<str:pk>/', edit_event, name='update-event-form'),
    path('delete-event-form/<str:pk>/', delete_event, name='delete-event-form'),
    path('update-student-hub-event/<str:pk>/', edit_students_event, name='update-student-hub-event'),
    path('update-student-form-event/<str:pk>/', edit_students_form_event, name='update-student-form-event'),
    path('delete-student-form-event/<str:pk>/', delete_students_event, name='delete-student-form-event'),
    path('update-teacher-hub-event/<str:pk>/', edit_teachers_event, name='update-teacher-hub-event'),
    path('update-teacher-form-event/<str:pk>/', edit_teachers_form_event, name='update-teacher-form-event'),
    path('delete-teacher-form-event/<str:pk>/', delete_teachers_event, name='delete-teacher-form-event'),

]